version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web
    ports:
      - "8000:8000"
    env_file:
      - env/.env.dev
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.dev.db

volumes:
  postgres_data: